# Generated by Django 5.1.4 on 2026-06-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rows', models.JSONField(default=list)),
                ('params', models.JSONField(default=dict)),
                ('mode', models.CharField(default='clean', max_length=10)),
                ('filters', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
