# Generated by Django 5.1.4 on 2026-06-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
